name: Build and Register Machnet as Latest

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push_machnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Machnet Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/machnet:latest
          target: machnet
          file: ./Dockerfile
          cache-from: type=gha,ref=ghcr.io/${{ github.repository }}/machnet_build_base:latest
          cache-to: type=gha,mode=max
